### ISSUE TITLE
Books and more

### ISSUE THREAD

**Issue by kajvans** [Yooooomi/media-center#1]
Does the server also support books and audiobooks. And how does it compare to jellyfin/plex and all the arr software?

**Comment by Yooooomi** [comment]
Ow hello there, this is **really** early development. It does not support much as of today. I'm focusing on movies and tv shows and **especially** stability.
It supports very heavy video files, thanks to the native home made VLC player. However, as I always do, I will primarily focus on what interests me in this project, and books and audiobooks are not a part of it now. 

I will lock issues for now as this is not even a first version of the product.
